config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :shelters, only: [ :index, :show, :new, :create ] do
    resources :animals, only: [ :create, :new ]
  end

  resources :animals, only: [ :show ] do
    resources :requests, only: [ :new, :create ]
  end

  resources :dashboard, only: [ :index ]
  patch "requests/:id/accept", to: "requests#accept", as: :accept
  patch "requests/:id/decline", to: "requests#decline", as: :decline

  resources :requests, only: :show

  resources :chatrooms, only: :show do
    resources :messages, only: :create
  end
end

app/models/shelter.rb
class Shelter < ApplicationRecord
  belongs_to :user
  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?
  has_one_attached :photo
  has_many :animals
  belongs_to :user
  validates :name, :address, :description, presence: true
end

app/controllers/shelters_controller.rb
class SheltersController < ApplicationController
  skip_before_action :authenticate_user!, only: :index

  def index
    @shelters = policy_scope(Shelter)
    if params[:pickup].present?
      @shelters = Shelter.near(params[:pickup], 800)
    elsif params[:dropoff].present?
      @shelters = @shelters.joins(:animals).where("animals.dropoff ILIKE ?", "%#{params[:dropoff].split(",").first}%")
    elsif params[:pickup].present? && params[:dropoff].present?
      @shelters.joins(:animals).where("animals.dropoff ILIKE ?", "%#{params[:dropoff]}%").near(params[:pickup], 800)
    end

    @markers = @shelters.geocoded.map do |shelter|
      {
        lat: shelter.latitude,
        lng: shelter.longitude,
        infoWindow: render_to_string(partial: "info_window", locals: { shelter: shelter }),
        image_url: helpers.asset_url('logopaw.jpg')
      }
    end
  end

  def show
    @shelter = Shelter.find(params[:id])
    authorize @shelter
  end

  def new
    @shelter = Shelter.new
    authorize @shelter
  end

  def create
    @shelter = Shelter.new(shelter_params)
    @shelter.user = current_user
    authorize @shelter
    if @shelter.save
      redirect_to shelter_path(@shelter), notice: "Shelter was successfully created."
    else
      render :new
    end
  end

  def edit
    @shelter = Shelter.find[params[:id]]
  end

  def update
    @shelter = Shelter.find(params[:id])
    if @shelter.update(params[shelter_params])
      redirect_to shelter_path(@shelter), notice: "Shelter successfully updated."
    else
      render :edit
    end
  end

  private

  def shelter_params
    params.require(:shelter).permit(:name, :address, :description, :photo)
  end
end

app/views/shelters/_info_window.html.erb
<p> <strong> <%= shelter.name %>  </strong> </p>
<p> <%= shelter.address %> </p>

app/views/shelters/index.html.erb
<style></style>
<div class="container search-bar justify-content-center" style="margin-top: 40px;">
  <div search-center>
    <%= form_tag shelters_path, method: :get, class: "search-form algolia-places-shelters" do %>
    <%= text_field_tag :pickup, params[:pickpup], class: "form-control lato", placeholder: "Where could you pick up the animal?" %>
    <%= text_field_tag :dropoff, params[:dropoff], class: "form-control lato shelter-index-input", placeholder: "Where could you drop off the animal?" %>
    <%= submit_tag "SEARCH SHELTERS", class: "prime-btn-landing lato" %>
    <% end %>
  </div>
</div>

<div class="d-flex" style="margin-left: 20px;">
  <div class="container h-100" style="margin-bottom: 60px">
    <div class="row align-middle">
      <% @shelters.each do |shelter| %>
        <div class="col-md-6 col-lg-6 column">
        <%= link_to shelter_path(shelter), class: "card-link" do %>
          <div class="card">
            <div class="card-banner" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url('<%= cl_image_path shelter.photo.key%>')">
              <div class="txt">
                <h1 class="shelter-h1"><%= shelter.name %></h1>
                <p class="shelter-p"><%= shelter.address %></p>
              </div>
            </div>
          </div>
          <% end %>
        </div>
      <% end %>
    </div>
  </div>
    <div id="map"
    style="width: 100%; height: 100vh; margin-top: 48px; margin-right: 20px;"
    data-markers="<%= @markers.to_json %>"
    data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>">
    </div>
</div>

<div class="container justify-content-center align-middle">
  <div class="button justify-content-center align-middle">
    <% if policy(Shelter).create? %>
      <%= link_to 'Create Shelter', new_shelter_path, class: 'sec-btn shelter-center justify-content-center' %>
    <% end  %>
  </div>
</div>

app/views/shelters/new.html.erb
<div class="container" style="margin-top: 20px;">
<%= link_to "Back", shelters_path, class: 'back-sec-btn' %>
</div>

<div class="container ahmo">
  <div class="row justify-content-center">
    <div class="col-xs-12 col-lg-8 col-md-6">
      <h1 class="text-center mt-4 lato">Add a Shelter</h1>
      <div class="form lato">
        <div class="container">
          <%= simple_form_for(@shelter) do |f| %>
            <%= f.input :name %>
            <%= f.input :address %>
            <%= f.input :description %>
            <label class="sec-btn sec-btn-file">Upload picture
            <span style="display:none;">
            <%= f.input :photo, as: :file, class: "hidden" %>
            </span>
            </label><br><br>
            <%= f.submit class: 'prime-btn'%>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/shelters/show.html.erb
<% if @shelter.photo.attached? %>
  <div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url('<%= cl_image_path @shelter.photo.key%>')">
<% else %>
  <div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url('https://source.unsplash.com/600x600/?dogs')">
<% end %>

  <div>
    <%= link_to "back",  shelters_path, class: 'back-sec-btn'%>
  </div>

    <div class="hero shelter-show-hero">
      <div class="container">
        <h1 class="open-sans lato ls-xlarge bold line-height-header"><%= @shelter.name %></h1>
        <h2 class="lato thin ls-xlarge line-height-h2"><%= @shelter.address %></h2>
        <p class="epsilon normal ls-medium line-height-text"><%= @shelter.description %>
        </p>
      </div>
    </div>
    <img src="<%= cl_image_path @shelter.user.avatar.key %>" class="card-animal-user avatar-large avatar-bordered" />
    <% if current_user == @shelter.user %>
          <%= link_to "+ Add Animal", new_shelter_animal_path(@shelter), id: "plus-btn" %>
        <% end %>
  </div>
  <div class="container">

    <div class="animal-cards">
      <div class="row">
        <% @shelter.animals.each do |animal|  %>
        <div class="col-md-4">
            <div class="card-animal">
              <% if animal.photos.attached? %>
                <%= cl_image_tag animal.photos.first.key %>
              <% end %>
              <div class="card-animal-infos">
                <div class="w-100">
                  <div class="card-animal-dropoff text-right"><p>Dropoff <i class="fas fa-map-marker"></i><%= animal.dropoff %></p></div>
                  <h2><%= animal.name %></h2>
                  <p><%= animal.medical_information[0..50]+"..." %></p>
                <div class="detail-link">
                 <%= link_to 'MORE DETAILS', animal_path(animal), class: 'prime-btn' %>
                 </div>
              </div>
          </div>
          </div>
        </div>
        <% end %>
      </div>
  </div>
</div>