config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :shelters, only: [ :index, :show, :new, :create ] do
    resources :animals, only: [ :create, :new ]
  end

  resources :animals, only: [ :show ] do
    resources :requests, only: [ :new, :create ]
  end

  resources :dashboard, only: [ :index ]
  patch "requests/:id/accept", to: "requests#accept", as: :accept
  patch "requests/:id/decline", to: "requests#decline", as: :decline

  resources :requests, only: :show

  resources :chatrooms, only: :show do
    resources :messages, only: :create
  end
end

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
    <footer class="site-footer">
      <div class="container">
        <div class="row">
          <div class="col-sm-12 col-xs-6 col-md-3">
            <h6>TravelPaws</h6>
            <%= render "shared/sausage-dog-animation"%>
          </div>

          <div class="col-sm-12 col-xs-6 col-md-6">
            <h6>About</h6>
            <p class="text-justify footer-p">We strive to help animal shelters to find volunteers who can become travel guardians for adopted animals and help them reach their new forever homes. Join us in our mission to to end animal homelessness in Europe!</p>
          </div>

          <div class="col-sm-12 col-xs-6 col-md-3">
            <h6>Quick Links</h6>
            <ul class="footer-links">
              <li><a href="/">Home</a></li>
              <li><a href="/shelters">Shelters</a></li>
              <li><a href="/shelters/new">Create a shelter</a></li>
              <li><a href="/dashboard">Dashboard</a></li>
              <li><a href="/">Profile</a></li>
            </ul>
          </div>
        </div>
        <hr>
      </div>
      <div class="container">
        <div class="row">
          <div class="col-md-8 col-sm-6 col-xs-12">
            <p class="copyright-text">Copyright &copy; 2021 All Rights Reserved by TravelPaws
            </p>
          </div>

          <div class="col-md-4 col-sm-6 col-xs-12">
            <ul class="social-icons">
              <li><a class="facebook" href="#"><i class="fab fa-facebook"></i></a></li>
              <li><a class="twitter" href="#"><i class="fab fa-twitter"></i></a></li>
              <li><a class="dribbble" href="#"><i class="fab fa-dribbble"></i></a></li>
              <li><a class="linkedin" href="#"><i class="fab fa-linkedin"></i></a></li>
            </ul>
          </div>
        </div>
      </div>
</footer>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="d-flex align-items">

    <%= link_to "Travel", root_path, class: "navbar-brand .link-styling-navbar lato mr-0" %>
    <div class="d-flex align-items-center">
      <i class="fas fa-paw"></i>
    </div>
   <%= link_to "Paws", root_path, class: "navbar-brand .link-styling-navbar lato" %>
  </div>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>


  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if user_signed_in? %>
        <li class="nav-item">
          <%= link_to "Home", root_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "All shelters", shelters_path , class: "nav-link" %>
        </li>
         <li class="nav-item">
          <%= link_to "Create a Shelter", new_shelter_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "My Dashboard", dashboard_index_path, class: "nav-link"%>
        </li>
        <li class="nav-item dropdown">
        <% if current_user.avatar.attached?  %>
          <%= cl_image_tag current_user.avatar.key, height: 40, width: 40, crop: :fill, class: "avatar", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
        <% else %>
          <%= image_tag "https://media.defense.gov/2020/Feb/19/2002251686/700/465/0/200219-A-QY194-002.JPG", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
        <% end %>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <%= link_to "My Profile", dashboard_index_path, class: "dropdown-item" %>
            <%= link_to "Shelter Profile", dashboard_index_path, class: "dropdown-item" %>
            <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
          </div>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "Login", new_user_session_path, class: "nav-link" %>
        </li>
      <% end %>
    </ul>
  </div>
</div>