config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :shelters, only: [ :index, :show, :new, :create ] do
    resources :animals, only: [ :create, :new ]
  end

  resources :animals, only: [ :show ] do
    resources :requests, only: [ :new, :create ]
  end

  resources :dashboard, only: [ :index ]
  patch "requests/:id/accept", to: "requests#accept", as: :accept
  patch "requests/:id/decline", to: "requests#decline", as: :decline

  resources :requests, only: :show

  resources :chatrooms, only: :show do
    resources :messages, only: :create
  end
end

app/models/animal.rb
class Animal < ApplicationRecord
  has_many_attached :photos
  belongs_to :shelter
  has_many :requests
  validates :name, :animal_type, :weight, :size, :age, :medical_information, :description, presence: true
end

app/controllers/animals_controller.rb
class AnimalsController < ApplicationController
  skip_before_action :authenticate_user!, only: :index

  def index
    @animals = policy_scope(Animal)
  end

  def show
    @animal = Animal.find(params[:id])
    @request = Request.new
    authorize @animal
  end

  def new
    @shelter = Shelter.find(params[:shelter_id])
    @animal = Animal.new
    authorize @animal
  end

  def create
    @shelter = Shelter.find(params[:shelter_id])
    @animal = Animal.new(animal_params)
    @animal.shelter = @shelter
    authorize @animal
    if @animal.save
      redirect_to animal_path(@animal), notice: "Animal was successfully created."
    else
      render :new
    end
  end

  def edit
    @animal = Animal.find[params[:id]]
  end

  def update
    @animal = Animal.find(params[:id])
    if @animal.update(params[animal_params])
      redirect_to animal_path(@animal), notice: "Animal was successfully updated."
    else
      render :edit
    end
  end

  private

  def animal_params
    params.require(:animal).permit(:name, :animal_type, :weight, :size, :age, :medical_information, :race, :description, :dropoff, photos: [])
  end
end

app/views/animals/new.html.erb
<div class="container">
<%= link_to "Back", shelter_path(@shelter), class: "back-sec-btn mt-4" %>
</div>

<div class="container ahmo">
  <div class="row justify-content-center">
    <div class="col-xs-12 col-lg-8 col-md-6">
    <h1 class="text-center mt-4 lato">Add an animal to the shelter</h1>
      <div class="form">
        <div class="container">
          <%= simple_form_for [@shelter, @animal] do |f| %>
            <%= f.input :name %>
            <%= f.input :animal_type %>
            <%= f.input :weight %>
            <%= f.input :size %>
            <%= f.input :age %>
            <%= f.input :medical_information %>
            <%= f.input :race %>
            <%= f.input :description %>
            <%= f.input :dropoff %>
            <label class="sec-btn sec-btn-file">Upload picture
            <span style="display:none;">
            <%= f.input :photos, as: :file, input_html: { multiple: true }, class: "hidden" %>
            </span>
            </label><br><br>
            <%= f.submit "Create", class: "prime-btn" %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/animals/show.html.erb
<div class="container ml-1">
  <%= link_to 'Back', shelters_path, class: 'back-sec-btn mt-2'%>
</div>


<div class="container-fluid d-flex mb-5">
  <div class="row mt-5">
    <div class="col-8">
      <div class="card-product">
        <div id="card-img">
          <% if @animal.photos.attached? %>
            <div id="carouselExampleControls" class="carousel slide" data-ride="carousel">
                <div class="carousel-inner">
                  <%   @animal.photos.each_with_index do |photo, index | %>
                  <div class="<%= index == 0 ? 'carousel-item active' : 'carousel-item' %>">
                    <%= cl_image_tag photo.key, height: 600, width: 500, crop: :fill,  class: "d-block" %>
                  </div>
                  <% end %>
                </div>

              <a class="carousel-control-prev" href="#carouselExampleControls" role="button" data-slide="prev">
                <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                <span class="sr-only">Previous</span>
              </a>
              <a class="carousel-control-next" href="#carouselExampleControls" role="button" data-slide="next">
                <span class="carousel-control-next-icon" aria-hidden="true"></span>
                <span class="sr-only">Next</span>
              </a>
            </div>

          <% end %>
        </div>

        <div class="card-product-infos d-flex flex-column justify-content-between h-100 py-5">
          <h1 class="headers-font lato bold"> <strong> <%= @animal.name %> </strong> </h1>
          <div class="lato normal w-100">
            <div class="container">
              <div class="row">
                <div class="col-4">
                  <div class="row my-3">Destination:</div>
                  <div class="row my-3">Weight (kg):</div>
                  <div class="row my-3">Size:</div>
                  <div class="row my-3">Race:</div>
                  <div class="row my-3">Medical information:</div>
                </div>

                <div class="col-8">
                  <div class="row my-3"><%= @animal.dropoff %></div>
                  <div class="row my-3"><%= @animal.weight %></div>
                  <div class="row my-3"><%= @animal.size %></div>
                  <div class="row my-3"><%= @animal.race %></div>
                  <div class="row my-3"><%= @animal.medical_information %></div>
                </div>
              </div>
            </div>
          </div>

          <div class="card-product-description lato">
            <h5>About <%= @animal.name %> </h5>
            <p> <em><%= @animal.description %> </em> </p>
          </div>
        </div>
      </div>


    </div>
    <div class="col-4">
      <div class="shelter-form h-100 px-4 d-flex flex-column justify-content-center">
        <div class="lato normal">
          <h5><strong>Get in touch with the shelter:</strong></h5>
          <%= simple_form_for [@animal, @request] do |f| %>
            <div class="button-fix">
              <%= f.input :message, input_html: {rows: 8} %>
              <label class="sec-btn sec-btn-file">Upload Passport
                <span style="display:none;">
                  <%= f.input :passport, as: :file, class: "hidden" %>
                </span>
                </label>
              <%= f.submit "Become my Guardian", class: "center-btn prime-btn justify-content-center" %>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>


</div>